Add `@MustCallAlias` annotations
typetools/jdk pull request #135
Opened 2022-06-25 04:50 UTC by mernst

2022-06-27 16:08 UTC, kelloggm requested changes
Tests are failing, I think because of some kind of configuration problem. I only looked at the added annotations, not at the changes to the CI setup or the JTREG tests.

2022-06-27 16:08 UTC, kelloggm commented on src/java.base/share/classes/java/util/Arrays.java
> +    public static @MinLen(2) String toString(@PolyMustCall @PolyNull @PolyInterned Object @PolyMustCall @Nullable [] a) {
This `@PolyMustCall` doesn't make sense to me, for two reasons:
1. `toString` itself shouldn't care what `MustCall` types its arguments have
2. even if, for some reason, we do want to annotate this argument to `toString`, `@PolyMustCall` on both the component type and on the array itself seems wrong: the array itself won't have a must-call obligation (at least, as the MustCall type system is used by the RLC), and even if it does I don't see a reason why we need to LUB its type with the MustCall types of the array components. Can you explain the reason for these annotations?

2022-06-27 16:08 UTC, kelloggm commented on src/java.base/share/classes/java/util/zip/ZipFile.java
> +      "the InputStream also closes the ZipEntry."})
I agree this is unclear. A brief web search didn't turn up any better information, so I think for now assuming that this method has a standard contract and that the documentation is a bit unclear is the right thing to do. Thanks for the comment that explains your reasoning.

2022-06-28 19:06 UTC, mernst commented
@kelloggm Can you take another look?  I think I will have the build problems corrected (by pulling master, so there are no such changes here) shortly.

2022-06-28 20:39 UTC, kelloggm approved these changes
Annotations LGTM

2022-06-29 03:50 UTC, closed without merging